// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:106791476366:web:e357da4340bfd81b087ddf',
    messagingSenderId: '106791476366',
    projectId: 'abonosapp-6507a',
    authDomain: 'abonosapp-6507a.firebaseapp.com',
    storageBucket: 'abonosapp-6507a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:106791476366:android:e357da4340bfd81b087ddf',
    messagingSenderId: '106791476366',
    projectId: 'abonosapp-6507a',
    storageBucket: 'abonosapp-6507a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:106791476366:ios:e357da4340bfd81b087ddf',
    messagingSenderId: '106791476366',
    projectId: 'abonosapp-6507a',
    storageBucket: 'abonosapp-6507a.appspot.com',
    iosClientId: '1:106791476366:ios:e357da4340bfd81b087ddf',
    iosBundleId: 'com.example.movil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:106791476366:ios:e357da4340bfd81b087ddf',
    messagingSenderId: '106791476366',
    projectId: 'abonosapp-6507a',
    storageBucket: 'abonosapp-6507a.appspot.com',
    iosClientId: '1:106791476366:ios:e357da4340bfd81b087ddf',
    iosBundleId: 'com.example.movil',
  );
} 